name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./completed/CryptoTicker

    steps:
    - uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    

    - uses: azure/docker-login@v1
      with:
        login-server: blazorwebapp.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t blazorwebapp.azurecr.io/cryptoticker:${{ github.sha }}
        docker push blazorwebapp.azurecr.io/cryptoticker:${{ github.sha }}  
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'crypto-ticker'
        images: 'blazorwebapp.azurecr.io/cryptoticker:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
